#=========================================
# STRUCTURAL EQUATION MODELLING - WORKSHOP
#=========================================

1. OPENING VIGNETTE (EXAMPLE)
2. WHAT IS R? 
3. R FOR ADVANCED VISUALIZATION (INFOGRAPHICS)
2. SEM - BASICS 
3. PACKAGES
  3.1. SEM PACKAGE
  3.2. LAVAAN PACKAGE
  3.3. PSYCH PACKAGE
6. SEMPLOTS